Fix gpg and group name
xcoo/metabill pull request #2
Opened 2021-11-22 06:43 UTC by kbaba1001

Because I couldn't deploy to clojars, I fixed group name and gpg-key setting.

2021-11-24 05:17 UTC, kbaba1001 commented on lein-metabill/project.clj
> -  :dependencies [[xcoo/metabill "0.1.0"]]
I had forgot to fix this line, so I fixed it and updated lein-metabill version.

2021-11-25 08:55 UTC, federkasten requested changes
Please fix the following two points in the README;

1. Wrong namespace `xcoo/` is remaining.
2. `with-commit-hash` usage description (with screenshot) is missing.

In addition, as a comment, I think it would be more helpful to output `metabill.edn` in `target/` or `resources/` where the classpaths are active, rather than in the top directory. Is there any reason to put it in the top directory? In this case, users need to manually add `metabill.edn` to classpaths for production builds.

2021-11-25 08:55 UTC, federkasten commented on lein-metabill/project.clj
> -  :signing {:gpg-key "developer@xcoo.jp"})
Please revert gpg signing :thinking: This is a very important setting.

2021-12-05 03:37 UTC, federkasten approved these changes
Merge once. I'll make some additional changes on my end :ok_man:

2021-12-05 03:37 UTC, merged