fix: Do not throw exception when metabill resource file does not exist.
xcoo/metabill pull request #3
Opened 2022-03-14 02:20 UTC by lambdadbmal

2022-03-14 02:29 UTC, federkasten requested changes

2022-03-14 02:29 UTC, federkasten commented on metabill/project.clj
> +(defproject jp.xcoo/metabill "0.1.4"
```suggestion
(defproject jp.xcoo/metabill "0.1.4-SNAPSHOT"
```

2022-03-14 02:29 UTC, federkasten commented on metabill/src/metabill/core.clj
> +      nil)))
And additionally, could you please add error handling escpecially for edn parse errors?

2022-03-17 08:04 UTC, federkasten commented on metabill/src/metabill/core.clj
> +        (catch Exception _ nil))
I don’t think it is good to ignore all `Exceptions and squash the result to `nil`. :thinking: 

Please fix it again to handle exceptions separately, such as EDN parse error or some other error. In addition, please output warning logs to the stderr.

2022-03-23 02:29 UTC, federkasten approved these changes

2022-03-23 02:29 UTC, federkasten commented on metabill/src/metabill/core.clj
> +(def ^:dynamic metabill-filename "metabill_err.edn")
```suggestion
(def ^:dynamic metabill-filename "metabill.edn")
```

2022-03-23 02:41 UTC, athos commented on metabill/src/metabill/core.clj
> +  (println msg)
Is this `println` intended? It would duplicate the same message to both stdout and stderr.

2022-03-30 04:11 UTC, federkasten approved these changes
LGTM :ok_man: Thanks!

2022-03-30 04:11 UTC, merged